### PR TITLE
improve jetstate ,init return a class to work better

### PR DESCRIPTION
**Pull request by fardad-dev**

### CODE REVIEW

**Comment by behnammodi** [comment]
thank's, i did not accept because it is big break in module and this module used in:

[react-jet](https://www.npmjs.com/package/react-jet) 
[react-beep](https://www.npmjs.com/package/react-beep)

**Comment by fardad-dev** [comment]
it's true
I will think about these modules

**Comment by fardad-dev** [comment]
please check this module
https://github.com/hosseinmd/reststate

**Comment by behnammodi** [comment]
great, good luck

**Pull request closed without merging**
